### ISSUE TITLE
Define a strategy for keeping notes

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/granger#2]

**Comment by SofiaVatti** [comment]
Notes:
1) Να μπορω να αλλάζω το size + length των ριζών και το medicament μετά την προσθίκη τους
2) Να υπάρχει κουμπί για ολοκλήρωση της θεραπείας που να φαίνεται στο activity feed 
3) Να μπορώ να προσθέσω ρίζες χωρίς να χρειάζεται να κάνω save

**Comment by vaslabs** [comment]
Need a better strategy for 2
"Να υπάρχει κουμπί για ολοκλήρωση της θεραπείας που να φαίνεται στο activity feed"
